language: go
services: docker
install:
- true
script:
- make cibuild
- make cipackage
deploy:
  provider: packagecloud
  username: auxesis
  repository: collectd
  dist: ubuntu/xenial
  token:
    secure: "CBcK/k1XLEaeshVsUAhjv+B0OWcprTH2tkMhwl517iQ0RR25hg4xl0B8K6DoCnu6u2ylbXYl6uZC283EhJI/hk6Jtl+p5+LP2FvSV8wCUtIJW9v+ed6poPoQLhH+i2GCKQbFolP054MBqmlYag2qzMB247JSmJrEzkQefbvGiY4D01+m5N1hvo/uArBCGFsUTWuOAnlALkreL/P+fCyPm3Ppi45DvXo17ifSSubaSX7jzuQ5Ju7k3q/1CBRZJn+rNorK6gzqUcfQt0MSsCLzf4SVCOv67vujk77nQX/hMyaWTUjeMikvxm89S3+jcTsV/1wh1kePoRVjYn+Eg7QuEhKWdYBi8OYN+ksg98rlIbrre0Bck6FI+sfR2LLBTFRbGCSHlyArEtdkKOj0VyrYqpCIRaDJ+3sJSNAIcdfiUrqo5LqHtTfE9mScMv4ogXlLjcTZoZKbbryX+z92TUAmip+oETGqyIRdmyM0iLuh69avGlCsvWsHwrKXjXDxk28SqKt5IdmvUVjWnerye48rNkCGgUmAHg9+oSvDFRz8VKbQALhqLhs/M/zgRDPPFblDNiCWuRN+/DzulCs4bTA6ApS9BklSNXKp/sDAWucgj41mpJ8DUyNXRwoazH6Hbu+JUU28NB2bowTDpR3zcO0WX4Sh7bGpubRvX6zrCi/IJiI="
  local-dir: packages
