language: go
install:
- true
script:
- make cibuild
- make cipackage
deploy:
  provider: packagecloud
  username: auxesis
  token:
    secure: u1pUxLChlc6bmCLmWzZ0jAHozRQ3xwQUX6VcfpSNXqMqQ0Z2Z2dbB8S5i7LSTOcuT+FW+JTmi7y8rG2VzEXktlAVtRwah1ot6zwtny1ONa4vctdiOWvZYUqLbKhPbjqm306KIqZbZS4R3fdfVhzp3cF/TQ0zr2k7XJLQ/ge4lshLOSriulCQezVKtuQ73ieYB4O4CubxWh6TrkqxW/yOmGhLLiC80QDLZdhCoea9kWK6sCtoVtLdOGUVj5C+7bjV8SUY5oAtzIUJqPb3ghpBqxZNagIjlagA1qV2VyPcGIWP4Tz8VETcZ8yRMFN22w14tcmxIb0H6QwOsh52S3qRcCYASQ3POkQcbkpDrr1MoRm5Wr0E28gKt4MiXBs9u2g8R51K2kPPMLhZWfkJE3Q0impKRfJ4rz+RoF4V3DtRhRgmfYDw9aWIp58fCRTxoS7ybL6XG14SlmIWUnMu7qeBPQJMmrgZq+YO6AK5W1nirkptruALuUjrgJMSnOrBp8uP1MiPNAPT4kKVlztloxwNGTiyzphILfNyVx6/K6IthvHaRxhqj59lz7jH6qKXTWKxHOr8v4MuMD6jHKzV7Ad5DNXISBzQ79CprSTbJ8Mc2aOf/JB7WMXizeq5hRVx1G0KkJkaGjPsNMor0H7qyKrukhBh6t/be2YtxITs1RcCLsw=
